"""empty message

Revision ID: 2a40bd6d1290
Revises: None
Create Date: 2014-06-21 17:09:09.270477

"""

# revision identifiers, used by Alembic.
revision = '2a40bd6d1290'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('registered_on', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
